import assert from 'node:assert/strict'
import { existsSync, readFileSync } from 'node:fs'
import test from 'node:test'
import { createComponentLoader, React, renderToStaticMarkup, Link, descendants, textContent } from './component-runtime.mjs'

const source = (path) => readFileSync(new URL(path, import.meta.url), 'utf8')
const css = source('../../app/globals.css')
const packageJson = JSON.parse(source('../../package.json'))
const runner = source('../../tests/run.mjs')
const testingGuide = source('../../document/process/testing.md')
const load = createComponentLoader({ 'next/link': { default: Link } })
const identity = load('components/ui/product-identity.ts')

test('TC-35-01 typography roles keep one hierarchy and do not scale every role the same way', () => {
  assert.equal(identity.TYPOGRAPHY_ROLES.length, 13)
  assert.equal(identity.typographyScaleIsHierarchical(), true)
  assert.equal(identity.numericRolesStayDistinct(), true)
  const snap = identity.responsiveTypeSnapshot()
  assert.equal(snap.desktopDisplay, identity.TYPOGRAPHY.display.maxRem)
  assert.ok(snap.desktopDisplay > snap.mobileDisplay)
  assert.ok(snap.mobileDisplay < 1.7)
  assert.equal(snap.mobileButton, snap.desktopButton)
  assert.equal(snap.mobileLabel, snap.desktopLabel)
  assert.ok(snap.desktopDisplay - snap.mobileDisplay > snap.desktopCaption - snap.mobileCaption)
  assert.equal(identity.fluidSizeRem('display', Number.NaN), identity.TYPOGRAPHY.display.minRem)
  for (const role of identity.TYPOGRAPHY_ROLES) {
    assert.ok(css.includes(identity.typographyRule(role)), role)
  }
})

test('TC-35-02 font strategy stays on two variable families with a fallback stack', () => {
  assert.equal(identity.fontStrategyIsRestrained(), true)
  assert.deepEqual([...identity.FONT_STRATEGY.families], ['Geist Sans', 'Geist Mono'])
  assert.match(css, /--font-sans:\s*var\(--font-geist-sans\), ui-sans-serif, system-ui, sans-serif/)
  assert.match(css, /--font-mono:\s*var\(--font-geist-mono\), ui-monospace, SFMono-Regular, Menlo, monospace/)
  const layout = source('../../app/layout.tsx')
  assert.match(layout, /GeistSans/)
  assert.match(layout, /GeistMono/)
  assert.doesNotMatch(layout, /next\/font\/google|@fontsource/)
  assert.equal(identity.TYPOGRAPHY.kpiHero.numeric, true)
  assert.equal(identity.TYPOGRAPHY.data.numeric, true)
  assert.equal(identity.TYPOGRAPHY.code.className, 'type-code')
})

test('TC-35-03 iconography uses one stroke, category sizes, and motion only when it gives feedback', () => {
  for (const category of identity.ICON_CATEGORIES) {
    assert.equal(identity.iconMetrics(category).stroke, identity.ICON_STROKE)
  }
  assert.equal(identity.iconMetrics('navigation').size, 20)
  assert.equal(identity.iconMetrics('action').size, 18)
  assert.equal(identity.iconMetrics('status').size, 16)
  assert.equal(identity.iconMetrics('decorative').size, 24)
  assert.equal(identity.iconSizeClass(20), 'size-5')
  assert.equal(identity.iconSizeClass(18), 'size-[18px]')
  assert.equal(identity.iconMotion('decorative', 'refresh'), 'none')
  assert.equal(identity.iconMotion('decorative', 'success'), 'none')
  assert.equal(identity.iconMotion('action', 'refresh'), 'spin')
  assert.equal(identity.iconMotion('status', 'success'), 'reveal')
  assert.equal(identity.iconMotion('navigation', 'navigate'), 'nudge')
  assert.equal(identity.iconMotion('data', 'idle'), 'none')
  assert.equal(identity.usesIconWell('inline'), false)
  assert.equal(identity.usesIconWell('brand'), true)
  assert.equal(identity.usesIconWell('state'), true)
  assert.equal(identity.usesIconWell('kpi'), true)
  assert.match(css, /\[data-icon-motion='spin'\]/)
  assert.match(css, /@media \(prefers-reduced-motion: reduce\)[\s\S]*\[data-icon-motion='spin'\]/)
  const sidebar = source('../../components/layout/app-sidebar.tsx')
  assert.match(sidebar, /import \{[^}]+\} from 'lucide-react'/)
  assert.doesNotMatch(sidebar, /import \* as /)
  assert.match(sidebar, /category="navigation"/)
  assert.match(sidebar, /data-icon-purpose="brand"/)
  assert.match(sidebar, /className="icon-well /)
  assert.match(sidebar, /nav-rail type-nav h-11/)
})

test('TC-35-04 charts use semantic series, a non-color pattern, and restart only when the dataset changes', () => {
  assert.equal(identity.chartMeaningUsesMoreThanColor(), true)
  assert.equal(identity.chartColorVariable('primary'), 'var(--chart-primary)')
  assert.equal(identity.chartColorVariable('negative'), 'var(--chart-negative)')
  assert.equal(identity.chartPattern('primary'), 'solid')
  assert.equal(identity.chartPattern('comparison'), 'dashed')
  assert.equal(identity.chartPattern('neutral'), 'dot')
  assert.equal(identity.chartStrokeDasharray('comparison'), '6 4')
  assert.equal(identity.chartStrokeDasharray('neutral'), '1.5 6')
  assert.equal(identity.chartStrokeDasharray('primary'), undefined)
  assert.equal(identity.chartStrokeDasharray('secondary'), undefined)
  assert.equal(identity.CHART_GRID_PROPS.stroke, 'var(--chart-grid)')
  assert.equal(identity.CHART_GRID_PROPS.vertical, false)
  assert.equal(identity.CHART_AXIS_PROPS.tick.fill, 'var(--chart-axis)')
  assert.match(css, /--chart-primary:\s*var\(--chart-1\)/)
  assert.match(css, /--chart-positive:\s*var\(--success\)/)
  assert.match(css, /--chart-negative:\s*var\(--danger\)/)
  assert.match(css, /\.dark, \.special-dark \{[\s\S]*--chart-1:\s*#7fb7ff/)
  assert.match(css, /\.special-dark \{[\s\S]*--chart-grid:/)
  const previous = identity.chartDatasetKey('hours', 2, '2026-10-01', '2026-10-02')
  const next = identity.chartDatasetKey('hours', 3, '2026-10-01', '2026-10-03')
  assert.equal(identity.shouldRestartChartMotion(previous, next, 'dataset'), true)
  assert.equal(identity.shouldRestartChartMotion(previous, previous, 'dataset'), false)
  assert.equal(identity.shouldRestartChartMotion(previous, next, 'hover'), false)
  assert.equal(identity.shouldRestartChartMotion(previous, next, 'tooltip'), false)
  assert.equal(identity.shouldRestartChartMotion(null, next, 'filter-chrome'), false)
  assert.equal(identity.chartTooltipText(0), '0')
  assert.equal(identity.chartTooltipText(12.5), (12.5).toLocaleString())
  assert.equal(identity.chartTooltipText(''), null)
  assert.equal(identity.chartTooltipText(Number.NaN), null)
  assert.equal(identity.chartTooltipText(null), null)
  assert.equal(identity.chartTooltipHasValue(0), true)
  const dashboard = source('../../components/layout/dashboard-charts.tsx')
  const analysis = source('../../components/page/analysis/analysis-charts.tsx')
  for (const file of [dashboard, analysis]) {
    assert.match(file, /CHART_GRID_PROPS/)
    assert.match(file, /chartColorVariable\('(?:primary|secondary)'\)/)
    assert.match(file, /chartDatasetKey\(/)
  }
  assert.match(dashboard, /isAnimationActive=\{!prefersReducedMotion && data\.length <= 100\}/)
  assert.equal((analysis.match(/isAnimationActive=\{!prefersReducedMotion(?: && hoursChartData\.length <= 100)?\}/g) ?? []).length, 2)
  assert.match(css, /\[data-slot='chart-tooltip'\]\.chart-tooltip/)
})

test('TC-35-05 status and visual states communicate with glyph, words and a next action', () => {
  for (const kind of identity.STATUS_KINDS) {
    assert.equal(identity.statusCommunicatesWithoutColor(kind), true)
    assert.notEqual(identity.STATUS_TREATMENTS[kind].glyph, '')
    assert.notEqual(identity.STATUS_TREATMENTS[kind].label, '')
  }
  assert.notEqual(identity.STATUS_TREATMENTS.active.glyph, identity.STATUS_TREATMENTS.success.glyph)
  assert.notEqual(identity.STATUS_TREATMENTS.offline.glyph, identity.STATUS_TREATMENTS.inactive.glyph)
  assert.equal(identity.workItemStatusVisual('completed'), 'success')
  assert.equal(identity.workItemStatusVisual('blocked'), 'error')
  assert.equal(identity.workItemStatusVisual('cancelled'), 'disabled')
  assert.notEqual(identity.STATUS_TREATMENTS.error.glyph, identity.STATUS_TREATMENTS.disabled.glyph)
  assert.equal(identity.workItemStatusVisual('in-progress'), 'processing')
  assert.equal(identity.workItemStatusVisual('sa-testing'), 'pending')
  assert.equal(identity.workItemStatusVisual('pm-testing'), 'pending')
  assert.equal(identity.workItemStatusVisual('todo'), 'active')
  assert.equal(identity.workItemStatusVisual('backlog'), 'inactive')
  assert.equal(identity.workItemStatusVisual('invented'), 'info')
  for (const kind of identity.VISUAL_STATE_KINDS) {
    const state = identity.VISUAL_STATES[kind]
    assert.ok(state.title.length > 0, kind)
    assert.ok(state.description.length > 0, kind)
    if (kind !== 'loading') assert.ok(state.action.length > 0, kind)
  }
  assert.equal(identity.VISUAL_STATES.partial.description, 'ข้อมูลส่วนอื่นยังใช้งานได้')
  assert.deepEqual([...identity.SIGNATURES], ['identity-mark', 'type-display', 'type-kpi-hero', 'icon-well', 'chart-tooltip', 'nav-rail'])
  for (const name of identity.SIGNATURES) assert.match(css + source('../../components/layout/app-sidebar.tsx') + source('../../components/layout/summary-stat-card.tsx') + source('../../components/ui/chart.tsx') + source('../../components/layout/page-state.tsx'), new RegExp(name.replaceAll('-', '\\-')))
})

test('TC-35-06 page states keep alert, busy, danger and wrapping contracts while using the identity mark', () => {
  const { PageState } = load('components/layout/page-state.tsx')
  const html = (props) => renderToStaticMarkup(React.createElement(PageState, props))
  const loading = html({ kind: 'loading', title: 'กำลังโหลด Projects…', loadingLayout: 'cards' })
  assert.match(loading, /role="status" aria-busy="true"/)
  assert.match(loading, /motion-safe:animate-spin/)
  assert.match(loading, /data-visual="loading"/)
  assert.match(loading, /data-slot="identity-mark"/)
  assert.match(loading, /data-layout="cards"/)
  const empty = html({ title: 'ไม่พบ Project', description: 'ลองปรับตัวกรอง' })
  assert.match(empty, /role="status" aria-busy="false"/)
  assert.match(empty, /data-visual="records"/)
  assert.match(empty, /type-section content-wrap max-w-full/)
  assert.match(empty, /type-body content-wrap max-w-md/)
  assert.doesNotMatch(empty, /data-slot="skeleton"/)
  const error = html({ kind: 'error', title: 'โหลดไม่สำเร็จ', description: 'กรุณาลองใหม่' })
  assert.match(error, /role="alert"/)
  assert.match(error, /text-danger/)
  assert.match(error, /data-tone="danger"/)
  const partial = html({ kind: 'error', visual: 'partial', title: 'โหลดกราฟไม่สำเร็จ', description: 'ข้อมูลส่วนอื่นยังใช้งานได้' })
  assert.match(partial, /data-visual="partial"/)
  assert.match(partial, /role="alert"/)
})

test('TC-35-07 status badges, headings, partial chart failure and navigation keep the shared language', () => {
  const { WorkItemStatusBadge } = load('components/page/work-items/work-item-status-badge.tsx')
  const completed = renderToStaticMarkup(React.createElement(WorkItemStatusBadge, { status: 'completed' }))
  const blocked = renderToStaticMarkup(React.createElement(WorkItemStatusBadge, { status: 'blocked' }))
  assert.match(completed, /data-status="success"/)
  assert.match(completed, /data-slot="status-glyph"/)
  assert.match(completed, />Completed</)
  assert.match(blocked, /data-status="error"/)
  assert.match(blocked, />Blocked</)
  assert.notEqual(completed.includes('✓'), blocked.includes('✓'))
  const { PAGE_HEADING, PAGE_LEAD } = load('components/layout/page-layout.ts')
  assert.match(PAGE_HEADING, /page-heading type-display content-wrap min-w-0/)
  assert.match(PAGE_LEAD, /type-body/)
  const { SummaryStatCard } = load('components/layout/summary-stat-card.tsx')
  const metric = renderToStaticMarkup(React.createElement(SummaryStatCard, { label: 'Open', value: 8, emphasis: 'primary', interactive: true }))
  assert.match(metric, /type-kpi-hero/)
  assert.match(metric, /type-kpi-support/)
  assert.match(metric, /data-cinematic="kpi-primary"/)
  const { ChartLoadError } = load('components/layout/chart-load-error.tsx')
  const chartError = renderToStaticMarkup(React.createElement(ChartLoadError, { heightClass: 'h-[320px]', onRetry() {} }))
  assert.match(chartError, /role="alert"/)
  assert.match(chartError, /ข้อมูลส่วนอื่นยังใช้งานได้/)
  assert.match(chartError, /ลองโหลดกราฟอีกครั้ง/)
  assert.match(chartError, /h-\[320px\]/)
  assert.match(chartError, /data-visual="partial"/)
  const { ApplicationState } = load('components/layout/application-state.tsx')
  const missing = renderToStaticMarkup(React.createElement(ApplicationState, { kind: 'not-found' }))
  assert.match(missing, /data-visual="not-found"/)
  assert.match(missing, /ไม่พบหน้าที่ต้องการ/)
  assert.doesNotMatch(missing, /ลองอีกครั้ง/)
})

test('TC-35-08 product identity has a reusable unit runner and no Makefile target', () => {
  assert.equal(packageJson.scripts['test:frontend-identity'], 'node tests/run.mjs frontend-identity')
  assert.match(runner, /"frontend-identity": \{ files: \[join\(testRoot, "frontend-ui", "product-identity\.test\.mjs"\)\] \}/)
  assert.match(testingGuide, /pnpm test:frontend-identity[\s\S]*bash scripts\/test-unit\.sh frontend-identity/)
  assert.match(testingGuide, /ไม่มี Makefile target/)
  assert.equal(identity.FONT_STRATEGY.maxFamilies, 2)
})

function layerBodies(sourceText, layerName) {
  const bodies = []
  const token = `@layer ${layerName}`
  let cursor = 0
  while (cursor < sourceText.length) {
    const start = sourceText.indexOf(token, cursor)
    if (start === -1) break
    const open = sourceText.indexOf('{', start)
    let depth = 0
    let end = open
    for (let index = open; index < sourceText.length; index += 1) {
      if (sourceText[index] === '{') depth += 1
      else if (sourceText[index] === '}') {
        depth -= 1
        if (depth === 0) {
          end = index
          break
        }
      }
    }
    bodies.push(sourceText.slice(open + 1, end))
    cursor = end + 1
  }
  return bodies
}

test('TC-35-09 review regressions keep utility overrides, icon size, toast layout and search states', () => {
  const bodies = layerBodies(css, 'components')
  const components = bodies.join('\n')
  const outside = bodies.reduce((remaining, body) => remaining.replace(body, ''), css)
  assert.match(css, /@import "tailwindcss"/)
  assert.match(components, /\.type-kpi-hero \{/)
  assert.match(components, /\.icon-well \{/)
  assert.match(components, /\.nav-rail\[data-active='true'\]::before/)
  assert.doesNotMatch(outside, /\.type-kpi-hero \{/)
  assert.doesNotMatch(outside, /\.icon-well \{/)
  const { SummaryStatCard } = load('components/layout/summary-stat-card.tsx')
  const overdue = renderToStaticMarkup(React.createElement(SummaryStatCard, { label: 'Overdue', value: 2, valueClassName: 'text-danger' }))
  assert.match(overdue, /type-kpi-hero[^"]*text-danger/)
  assert.doesNotMatch(overdue, /sm:text-sm/)
  const { ToastMessage } = load('components/ui/toaster.tsx')
  const saved = ToastMessage({ title: 'บันทึกแล้ว', description: 'เก็บแล้ว', action: React.createElement('button', null, 'เลิกทำ') })
  const body = descendants(saved).find((element) => element.props?.['data-slot'] === 'toast-body')
  assert.equal(body.props['data-visual'], 'success')
  assert.match(textContent(body), /บันทึกแล้ว/)
  assert.doesNotMatch(textContent(body), /เลิกทำ/)
  assert.match(textContent(saved), /เลิกทำ/)
  const glyph = descendants(body).find((element) => element.props?.['data-slot'] === 'status-glyph')
  assert.equal(glyph.props['data-icon-motion'], 'reveal')
  const failed = ToastMessage({ title: 'Error', variant: 'destructive' })
  const failedGlyph = descendants(failed).find((element) => element.props?.['data-slot'] === 'status-glyph')
  assert.equal(failedGlyph.props['data-status'], 'error')
  assert.equal(failedGlyph.props['data-icon-motion'], 'none')
  const sidebar = source('../../components/layout/app-sidebar.tsx')
  assert.match(sidebar, /\[&_svg\[data-icon-category=navigation\]\]:size-5/)
  assert.match(sidebar, /\[&_svg\[data-icon-category=action\]\]:size-\[18px\]/)
  assert.match(sidebar, /size=\{ICON_SIZE_PX\.feature\}/)
  assert.match(sidebar, /intent="navigate"/)
  assert.match(source('../../components/page/work-items/work-item-grouped-list.tsx'), /visual="search"/)
  assert.match(source('../../components/page/daily-work/work-log-list.tsx'), /visual=\{searchQuery\.trim\(\) \? 'search' : 'activity'\}/)
  assert.match(source('../../app/projects/page.tsx'), /projectVisual/)
  assert.match(source('../../components/layout/dashboard-charts.tsx'), /visual="chart"/)
  assert.match(source('../../components/layout/dashboard-charts.tsx'), /useChartDatasetKey/)
  assert.match(source('../../components/page/analysis/analysis-charts.tsx'), /chartStrokeDasharray\('secondary'\)/)
  assert.match(source('../../components/page/work-items/gitlab-import-panel.tsx'), /intent=\{loading \? 'refresh' : 'idle'\}/)
  assert.equal(identity.loadFailureVisual('Failed to fetch'), 'network')
  assert.equal(identity.loadFailureVisual('Load failed'), 'network')
  assert.equal(identity.loadFailureVisual('NetworkError when attempting to fetch resource.'), 'network')
  assert.equal(identity.loadFailureVisual('โหลด Company ไม่สำเร็จ'), 'error')
  assert.equal(identity.VISUAL_STATE_APPLICABILITY.permission, 'not-applicable')
  assert.equal(identity.VISUAL_STATE_APPLICABILITY.search, 'rendered')
  const { PageState } = load('components/layout/page-state.tsx')
  const permission = renderToStaticMarkup(React.createElement(PageState, { visual: 'permission', title: identity.VISUAL_STATES.permission.title }))
  assert.match(permission, /data-visual="permission"/)
  assert.match(permission, /data-tone="warning"/)
  assert.match(permission, /text-warning/)
  const { WorkItemStatusBadge } = load('components/page/work-items/work-item-status-badge.tsx')
  const cancelled = renderToStaticMarkup(React.createElement(WorkItemStatusBadge, { status: 'cancelled' }))
  const blocked = renderToStaticMarkup(React.createElement(WorkItemStatusBadge, { status: 'blocked' }))
  assert.match(cancelled, /data-status="disabled"/)
  assert.match(blocked, /data-status="error"/)
  assert.notEqual(cancelled.includes('–'), blocked.includes('–'))
  assert.equal(existsSync(new URL('../../components/ui/chart-load-error.tsx', import.meta.url)), false)
  assert.match(source('../../components/layout/chart-load-error.tsx'), /from '\.\/page-state'/)
})
