sonar.projectKey=wasant-prds_project-management-system
sonar.projectName=Project Management System
sonar.sources=app,components,lib,prisma,scripts
sonar.tests=tests
sonar.test.inclusions=tests/**/*.test.mjs
sonar.exclusions=**/node_modules/**,**/.next/**,**/coverage/**
sonar.sourceEncoding=UTF-8
