-- Project Management System SQL target snapshot, issue #31.
-- PostgreSQL 16. Empty database only. This is not the active Prisma/runtime schema.
-- No business rows, credentials, roles, owners, or database names.
-- The migration runner owns BEGIN/COMMIT. Do not add transaction control here.
-- Apply only with scripts/sql-migrate.mjs and an explicit isolated target.
-- Timestamp defaults use Asia/Bangkok wall-clock time, independent of the client TimeZone.
-- Primary keys are BIGINT GENERATED BY DEFAULT AS IDENTITY
-- (START WITH 1 INCREMENT BY 1 NO CYCLE). Gaps are allowed. Do not renumber rows.
-- Every table also has an immutable random UUIDv4 public_id for client references.
-- Numeric keys remain internal; all relational FKs use id.
-- Naming: plural snake_case tables, snake_case columns, indexes and enum types.
-- Runtime evidence: app/api and lib, including Project DELETE relation counts.
-- Comment and Notification have no runtime queries and are excluded.
-- project_members, project_documents, project_milestones and activity_logs are
-- retained because the current Project DELETE handler queries their row counts.
-- schema_migrations is required by the SQL migration runner. The legacy ID
-- mapping table is excluded until a data migration actually uses it.
-- Names here require explicit Prisma mappings at the future SQL runtime cutover.
-- activity_logs are append-only; their foreign keys use RESTRICT on delete/update.
-- External reference project_id is a local PMS project, as written and compared
-- by lib/gitlab-issue-import.ts, so it is a BIGINT foreign key. External provider IDs stay TEXT.

CREATE FUNCTION pms_bangkok_now() RETURNS timestamp(3) WITHOUT TIME ZONE
LANGUAGE sql
VOLATILE
SET search_path = pg_catalog
AS $pms$
  SELECT pg_catalog.timezone('Asia/Bangkok', pg_catalog.clock_timestamp())::timestamp(3)
$pms$;

CREATE FUNCTION pms_bangkok_today() RETURNS date
LANGUAGE sql
VOLATILE
SET search_path = pg_catalog
AS $pms$
  SELECT (pg_catalog.timezone('Asia/Bangkok', pg_catalog.clock_timestamp()))::date
$pms$;

CREATE FUNCTION pms_stamp_timestamps() RETURNS trigger
LANGUAGE plpgsql
SET search_path = public, pg_catalog
AS $pms$
DECLARE
  preserve text;
  changed boolean;
BEGIN
  IF TG_OP = 'UPDATE' AND NEW.public_id IS DISTINCT FROM OLD.public_id THEN
    RAISE EXCEPTION '% public_id cannot be changed', TG_TABLE_NAME USING ERRCODE = '55000';
  END IF;
  preserve := pg_catalog.current_setting('pms.preserve_source_timestamps', true);
  IF TG_OP = 'INSERT' THEN
    IF preserve IS DISTINCT FROM 'on' THEN
      NEW.created_at := public.pms_bangkok_now();
      NEW.updated_at := NEW.created_at;
    END IF;
    RETURN NEW;
  END IF;
  IF preserve IS DISTINCT FROM 'on' THEN
    NEW.created_at := OLD.created_at;
    changed := (pg_catalog.to_jsonb(NEW) - 'created_at' - 'updated_at')
      IS DISTINCT FROM (pg_catalog.to_jsonb(OLD) - 'created_at' - 'updated_at');
    IF changed THEN
      NEW.updated_at := public.pms_bangkok_now();
    ELSE
      NEW.updated_at := OLD.updated_at;
    END IF;
  END IF;
  RETURN NEW;
END;
$pms$;

CREATE FUNCTION pms_stamp_created_at() RETURNS trigger
LANGUAGE plpgsql
SET search_path = public, pg_catalog
AS $pms$
BEGIN
  IF pg_catalog.current_setting('pms.preserve_source_timestamps', true) IS DISTINCT FROM 'on' THEN
    NEW.created_at := public.pms_bangkok_now();
  END IF;
  RETURN NEW;
END;
$pms$;

CREATE FUNCTION pms_reject_immutable_row() RETURNS trigger
LANGUAGE plpgsql
SET search_path = pg_catalog
AS $pms$
BEGIN
  RAISE EXCEPTION '% cannot be updated or deleted', TG_TABLE_NAME
    USING ERRCODE = '55000';
END;
$pms$;

CREATE FUNCTION pms_align_identity(target pg_catalog.regclass) RETURNS bigint
LANGUAGE plpgsql
SET search_path = public, pg_catalog
AS $pms$
DECLARE
  sequence_name text;
  max_id bigint;
BEGIN
  sequence_name := pg_catalog.pg_get_serial_sequence(target::text, 'id');
  IF sequence_name IS NULL THEN
    RAISE EXCEPTION 'identity sequence missing';
  END IF;
  EXECUTE format('SELECT max(id) FROM %s', target) INTO max_id;
  IF max_id IS NULL THEN
    PERFORM pg_catalog.setval(sequence_name, 1, false);
    RETURN 1;
  END IF;
  PERFORM pg_catalog.setval(sequence_name, max_id, true);
  RETURN max_id + 1;
END;
$pms$;

CREATE TYPE "work_item_kind" AS ENUM ('Incident', 'Issue', 'Task');
CREATE TYPE "work_item_priority" AS ENUM ('none', 'low', 'medium', 'high', 'urgent');
CREATE TYPE "work_item_role" AS ENUM ('Developer', 'infra', 'SA');
CREATE TYPE "work_item_status" AS ENUM ('backlog', 'todo', 'in-progress', 'blocked', 'sa-testing', 'pm-testing', 'completed', 'cancelled');
CREATE TYPE "user_theme" AS ENUM ('light', 'dark', 'special-dark');
CREATE TYPE "user_locale" AS ENUM ('th', 'en');

CREATE TABLE "users" (
    "id" BIGINT GENERATED BY DEFAULT AS IDENTITY (START WITH 1 INCREMENT BY 1 NO CYCLE) NOT NULL,
    "public_id" UUID NOT NULL DEFAULT pg_catalog.gen_random_uuid(),
    "email" TEXT NOT NULL,
    "name" TEXT NOT NULL,
    "password_hash" TEXT NOT NULL,
    "role" TEXT NOT NULL DEFAULT 'member',
    "avatar_url" TEXT,
    "phone" TEXT,
    "theme" "user_theme" NOT NULL DEFAULT 'light',
    "locale" "user_locale" NOT NULL DEFAULT 'th',
    "status" TEXT NOT NULL DEFAULT 'Active',
    "joined_at" TIMESTAMP(3) WITHOUT TIME ZONE NOT NULL DEFAULT public.pms_bangkok_now(),
    "created_at" TIMESTAMP(3) WITHOUT TIME ZONE NOT NULL DEFAULT public.pms_bangkok_now(),
    "updated_at" TIMESTAMP(3) WITHOUT TIME ZONE NOT NULL DEFAULT public.pms_bangkok_now(),
    CONSTRAINT "users_public_id_key" UNIQUE ("public_id"),
    CONSTRAINT "users_pkey" PRIMARY KEY ("id")
);

CREATE TABLE "companies" (
    "id" BIGINT GENERATED BY DEFAULT AS IDENTITY (START WITH 1 INCREMENT BY 1 NO CYCLE) NOT NULL,
    "public_id" UUID NOT NULL DEFAULT pg_catalog.gen_random_uuid(),
    "code" TEXT,
    "display_name" TEXT,
    "location" TEXT,
    "name" TEXT NOT NULL,
    "industry" TEXT,
    "email" TEXT,
    "phone" TEXT,
    "address" TEXT,
    "website_url" TEXT,
    "logo_url" TEXT,
    "description" TEXT,
    "created_at" TIMESTAMP(3) WITHOUT TIME ZONE NOT NULL DEFAULT public.pms_bangkok_now(),
    "updated_at" TIMESTAMP(3) WITHOUT TIME ZONE NOT NULL DEFAULT public.pms_bangkok_now(),
    CONSTRAINT "companies_public_id_key" UNIQUE ("public_id"),
    CONSTRAINT "companies_pkey" PRIMARY KEY ("id")
);

CREATE TABLE "projects" (
    "id" BIGINT GENERATED BY DEFAULT AS IDENTITY (START WITH 1 INCREMENT BY 1 NO CYCLE) NOT NULL,
    "public_id" UUID NOT NULL DEFAULT pg_catalog.gen_random_uuid(),
    "name" TEXT NOT NULL,
    "description" TEXT,
    "status" TEXT NOT NULL DEFAULT 'Planning',
    "priority" TEXT NOT NULL DEFAULT 'Medium',
    "start_date" DATE NOT NULL,
    "due_date" DATE NOT NULL,
    "budget_amount" DECIMAL(65,30),
    "spent_amount" DECIMAL(65,30) DEFAULT 0,
    "progress_percent" INTEGER NOT NULL DEFAULT 0,
    "color" TEXT,
    "created_at" TIMESTAMP(3) WITHOUT TIME ZONE NOT NULL DEFAULT public.pms_bangkok_now(),
    "updated_at" TIMESTAMP(3) WITHOUT TIME ZONE NOT NULL DEFAULT public.pms_bangkok_now(),
    "creator_id" BIGINT,
    "company_id" BIGINT NOT NULL,
    CONSTRAINT "projects_public_id_key" UNIQUE ("public_id"),
    CONSTRAINT "projects_pkey" PRIMARY KEY ("id")
);

CREATE TABLE "project_members" (
    "id" BIGINT GENERATED BY DEFAULT AS IDENTITY (START WITH 1 INCREMENT BY 1 NO CYCLE) NOT NULL,
    "public_id" UUID NOT NULL DEFAULT pg_catalog.gen_random_uuid(),
    "role" TEXT NOT NULL DEFAULT 'member',
    "joined_at" TIMESTAMP(3) WITHOUT TIME ZONE NOT NULL DEFAULT public.pms_bangkok_now(),
    "project_id" BIGINT NOT NULL,
    "user_id" BIGINT NOT NULL,
    "created_at" TIMESTAMP(3) WITHOUT TIME ZONE NOT NULL DEFAULT public.pms_bangkok_now(),
    "updated_at" TIMESTAMP(3) WITHOUT TIME ZONE NOT NULL DEFAULT public.pms_bangkok_now(),
    CONSTRAINT "project_members_public_id_key" UNIQUE ("public_id"),
    CONSTRAINT "project_members_pkey" PRIMARY KEY ("id")
);

CREATE TABLE "work_items" (
    "id" BIGINT GENERATED BY DEFAULT AS IDENTITY (START WITH 1 INCREMENT BY 1 NO CYCLE) NOT NULL,
    "public_id" UUID NOT NULL DEFAULT pg_catalog.gen_random_uuid(),
    "title" TEXT NOT NULL,
    "description" TEXT,
    "kind" "work_item_kind" NOT NULL,
    "priority" "work_item_priority" NOT NULL DEFAULT 'none',
    "functional_role" "work_item_role",
    "status" "work_item_status" NOT NULL DEFAULT 'backlog',
    "type_labels" TEXT[] DEFAULT ARRAY[]::TEXT[],
    "work_date" DATE,
    "due_date" DATE,
    "submitted_at" TIMESTAMP(3) WITHOUT TIME ZONE,
    "created_at" TIMESTAMP(3) WITHOUT TIME ZONE NOT NULL DEFAULT public.pms_bangkok_now(),
    "updated_at" TIMESTAMP(3) WITHOUT TIME ZONE NOT NULL DEFAULT public.pms_bangkok_now(),
    "project_id" BIGINT NOT NULL,
    "assignee_id" BIGINT NOT NULL,
    CONSTRAINT "work_items_public_id_key" UNIQUE ("public_id"),
    CONSTRAINT "work_items_pkey" PRIMARY KEY ("id")
);

CREATE TABLE "external_project_mappings" (
    "id" BIGINT GENERATED BY DEFAULT AS IDENTITY (START WITH 1 INCREMENT BY 1 NO CYCLE) NOT NULL,
    "public_id" UUID NOT NULL DEFAULT pg_catalog.gen_random_uuid(),
    "provider" TEXT NOT NULL DEFAULT 'gitlab',
    "instance_url" TEXT NOT NULL,
    "external_project_id" TEXT NOT NULL,
    "project_id" BIGINT NOT NULL,
    "approved_label_map" JSONB NOT NULL DEFAULT '{}'::JSONB,
    "first_sync_approved_at" TIMESTAMP(3) WITHOUT TIME ZONE,
    "created_at" TIMESTAMP(3) WITHOUT TIME ZONE NOT NULL DEFAULT public.pms_bangkok_now(),
    "updated_at" TIMESTAMP(3) WITHOUT TIME ZONE NOT NULL DEFAULT public.pms_bangkok_now(),
    CONSTRAINT "external_project_mappings_public_id_key" UNIQUE ("public_id"),
    CONSTRAINT "external_project_mappings_pkey" PRIMARY KEY ("id")
);

CREATE TABLE "external_work_item_references" (
    "id" BIGINT GENERATED BY DEFAULT AS IDENTITY (START WITH 1 INCREMENT BY 1 NO CYCLE) NOT NULL,
    "public_id" UUID NOT NULL DEFAULT pg_catalog.gen_random_uuid(),
    "provider" TEXT NOT NULL DEFAULT 'gitlab',
    "instance_url" TEXT NOT NULL,
    "external_project_id" TEXT NOT NULL,
    "external_issue_id" TEXT NOT NULL,
    "external_issue_number" TEXT NOT NULL,
    "external_url" TEXT NOT NULL,
    "project_id" BIGINT NOT NULL,
    "remote_created_at" TIMESTAMP(3) WITHOUT TIME ZONE NOT NULL,
    "remote_updated_at" TIMESTAMP(3) WITHOUT TIME ZONE NOT NULL,
    "last_synced_at" TIMESTAMP(3) WITHOUT TIME ZONE NOT NULL,
    "work_item_id" BIGINT NOT NULL,
    "created_at" TIMESTAMP(3) WITHOUT TIME ZONE NOT NULL DEFAULT public.pms_bangkok_now(),
    "updated_at" TIMESTAMP(3) WITHOUT TIME ZONE NOT NULL DEFAULT public.pms_bangkok_now(),
    CONSTRAINT "external_work_item_references_public_id_key" UNIQUE ("public_id"),
    CONSTRAINT "external_work_item_references_pkey" PRIMARY KEY ("id")
);

CREATE TABLE "project_milestones" (
    "id" BIGINT GENERATED BY DEFAULT AS IDENTITY (START WITH 1 INCREMENT BY 1 NO CYCLE) NOT NULL,
    "public_id" UUID NOT NULL DEFAULT pg_catalog.gen_random_uuid(),
    "name" TEXT NOT NULL,
    "description" TEXT,
    "due_date" TIMESTAMP(3) WITHOUT TIME ZONE NOT NULL,
    "status" TEXT NOT NULL DEFAULT 'Not Started',
    "created_at" TIMESTAMP(3) WITHOUT TIME ZONE NOT NULL DEFAULT public.pms_bangkok_now(),
    "updated_at" TIMESTAMP(3) WITHOUT TIME ZONE NOT NULL DEFAULT public.pms_bangkok_now(),
    "project_id" BIGINT NOT NULL,
    CONSTRAINT "project_milestones_public_id_key" UNIQUE ("public_id"),
    CONSTRAINT "project_milestones_pkey" PRIMARY KEY ("id")
);

CREATE TABLE "project_documents" (
    "id" BIGINT GENERATED BY DEFAULT AS IDENTITY (START WITH 1 INCREMENT BY 1 NO CYCLE) NOT NULL,
    "public_id" UUID NOT NULL DEFAULT pg_catalog.gen_random_uuid(),
    "name" TEXT NOT NULL,
    "description" TEXT,
    "file_url" TEXT NOT NULL,
    "file_size_bytes" INTEGER,
    "file_type" TEXT,
    "created_at" TIMESTAMP(3) WITHOUT TIME ZONE NOT NULL DEFAULT public.pms_bangkok_now(),
    "updated_at" TIMESTAMP(3) WITHOUT TIME ZONE NOT NULL DEFAULT public.pms_bangkok_now(),
    "project_id" BIGINT,
    "uploader_id" BIGINT,
    CONSTRAINT "project_documents_public_id_key" UNIQUE ("public_id"),
    CONSTRAINT "project_documents_pkey" PRIMARY KEY ("id")
);

CREATE TABLE "work_logs" (
    "id" BIGINT GENERATED BY DEFAULT AS IDENTITY (START WITH 1 INCREMENT BY 1 NO CYCLE) NOT NULL,
    "public_id" UUID NOT NULL DEFAULT pg_catalog.gen_random_uuid(),
    "description" TEXT,
    "remarks" TEXT,
    "hours" DECIMAL(65,30) NOT NULL,
    "work_date" DATE NOT NULL DEFAULT public.pms_bangkok_today(),
    "status" TEXT,
    "created_at" TIMESTAMP(3) WITHOUT TIME ZONE NOT NULL DEFAULT public.pms_bangkok_now(),
    "updated_at" TIMESTAMP(3) WITHOUT TIME ZONE NOT NULL DEFAULT public.pms_bangkok_now(),
    "user_id" BIGINT NOT NULL,
    "project_id" BIGINT,
    "work_item_id" BIGINT,
    CONSTRAINT "work_logs_public_id_key" UNIQUE ("public_id"),
    CONSTRAINT "work_logs_pkey" PRIMARY KEY ("id")
);

CREATE TABLE "activity_logs" (
    "id" BIGINT GENERATED BY DEFAULT AS IDENTITY (START WITH 1 INCREMENT BY 1 NO CYCLE) NOT NULL,
    "public_id" UUID NOT NULL DEFAULT pg_catalog.gen_random_uuid(),
    "action" TEXT NOT NULL,
    "entity" TEXT NOT NULL,
    "entity_id" TEXT NOT NULL,
    "description" TEXT,
    "metadata" JSONB,
    "created_at" TIMESTAMP(3) WITHOUT TIME ZONE NOT NULL DEFAULT public.pms_bangkok_now(),
    "user_id" BIGINT,
    "project_id" BIGINT,
    CONSTRAINT "activity_logs_public_id_key" UNIQUE ("public_id"),
    CONSTRAINT "activity_logs_pkey" PRIMARY KEY ("id")
);

CREATE TABLE "schema_migrations" (
    "id" BIGINT GENERATED BY DEFAULT AS IDENTITY (START WITH 1 INCREMENT BY 1 NO CYCLE) NOT NULL,
    "public_id" UUID NOT NULL DEFAULT pg_catalog.gen_random_uuid(),
    "version" TEXT NOT NULL,
    "checksum" TEXT NOT NULL,
    "schema_revision" TEXT NOT NULL,
    "status" TEXT NOT NULL,
    "applied_at" TIMESTAMP(3) WITHOUT TIME ZONE NOT NULL DEFAULT public.pms_bangkok_now(),
    "script_name" TEXT NOT NULL,
    "target_label" TEXT NOT NULL,
    CONSTRAINT "schema_migrations_public_id_key" UNIQUE ("public_id"),
    CONSTRAINT "schema_migrations_pkey" PRIMARY KEY ("id"),
    CONSTRAINT "schema_migrations_version_key" UNIQUE ("version"),
    CONSTRAINT "schema_migrations_checksum_format" CHECK ("checksum" ~ '^[0-9a-f]{64}$'),
    CONSTRAINT "schema_migrations_status_applied" CHECK ("status" = 'applied')
);

CREATE UNIQUE INDEX "users_email_key" ON "users"("email");
CREATE INDEX "users_email_idx" ON "users"("email");
CREATE UNIQUE INDEX "companies_code_key" ON "companies"("code");
CREATE INDEX "projects_status_idx" ON "projects"("status");
CREATE INDEX "projects_priority_idx" ON "projects"("priority");
CREATE INDEX "projects_creator_id_idx" ON "projects"("creator_id");
CREATE INDEX "projects_company_id_status_idx" ON "projects"("company_id", "status");
CREATE INDEX "project_members_project_id_idx" ON "project_members"("project_id");
CREATE INDEX "project_members_user_id_idx" ON "project_members"("user_id");
CREATE UNIQUE INDEX "project_members_project_id_user_id_key" ON "project_members"("project_id", "user_id");
CREATE INDEX "work_items_project_id_idx" ON "work_items"("project_id");
CREATE INDEX "work_items_assignee_id_idx" ON "work_items"("assignee_id");
CREATE INDEX "work_items_kind_idx" ON "work_items"("kind");
CREATE INDEX "work_items_status_idx" ON "work_items"("status");
CREATE INDEX "work_items_priority_idx" ON "work_items"("priority");
CREATE INDEX "work_items_work_date_idx" ON "work_items"("work_date");
CREATE INDEX "work_items_due_date_idx" ON "work_items"("due_date");
CREATE INDEX "work_items_created_at_idx" ON "work_items"("created_at");
CREATE INDEX "external_project_mappings_project_id_idx" ON "external_project_mappings"("project_id");
CREATE UNIQUE INDEX "external_project_mappings_source_key" ON "external_project_mappings"("provider", "instance_url", "external_project_id");
CREATE UNIQUE INDEX "external_work_item_references_work_item_id_key" ON "external_work_item_references"("work_item_id");
CREATE INDEX "external_work_item_references_project_id_idx" ON "external_work_item_references"("project_id");
CREATE UNIQUE INDEX "external_work_item_references_source_key" ON "external_work_item_references"("provider", "instance_url", "external_project_id", "external_issue_id");
CREATE INDEX "project_milestones_project_id_idx" ON "project_milestones"("project_id");
CREATE INDEX "project_documents_project_id_idx" ON "project_documents"("project_id");
CREATE INDEX "project_documents_uploader_id_idx" ON "project_documents"("uploader_id");
CREATE INDEX "work_logs_user_id_idx" ON "work_logs"("user_id");
CREATE INDEX "work_logs_project_id_idx" ON "work_logs"("project_id");
CREATE INDEX "work_logs_work_item_id_idx" ON "work_logs"("work_item_id");
CREATE INDEX "work_logs_work_date_idx" ON "work_logs"("work_date");
CREATE INDEX "activity_logs_user_id_idx" ON "activity_logs"("user_id");
CREATE INDEX "activity_logs_project_id_idx" ON "activity_logs"("project_id");
CREATE INDEX "activity_logs_entity_entity_id_idx" ON "activity_logs"("entity", "entity_id");
CREATE INDEX "activity_logs_created_at_idx" ON "activity_logs"("created_at");

ALTER TABLE "projects" ADD CONSTRAINT "projects_company_id_fkey" FOREIGN KEY ("company_id") REFERENCES "companies"("id") ON DELETE RESTRICT ON UPDATE CASCADE;
ALTER TABLE "projects" ADD CONSTRAINT "projects_creator_id_fkey" FOREIGN KEY ("creator_id") REFERENCES "users"("id") ON DELETE SET NULL ON UPDATE CASCADE;
ALTER TABLE "project_members" ADD CONSTRAINT "project_members_project_id_fkey" FOREIGN KEY ("project_id") REFERENCES "projects"("id") ON DELETE RESTRICT ON UPDATE CASCADE;
ALTER TABLE "project_members" ADD CONSTRAINT "project_members_user_id_fkey" FOREIGN KEY ("user_id") REFERENCES "users"("id") ON DELETE CASCADE ON UPDATE CASCADE;
ALTER TABLE "work_items" ADD CONSTRAINT "work_items_project_id_fkey" FOREIGN KEY ("project_id") REFERENCES "projects"("id") ON DELETE RESTRICT ON UPDATE CASCADE;
ALTER TABLE "work_items" ADD CONSTRAINT "work_items_assignee_id_fkey" FOREIGN KEY ("assignee_id") REFERENCES "users"("id") ON DELETE RESTRICT ON UPDATE CASCADE;
ALTER TABLE "external_project_mappings" ADD CONSTRAINT "external_project_mappings_project_id_fkey" FOREIGN KEY ("project_id") REFERENCES "projects"("id") ON DELETE RESTRICT ON UPDATE CASCADE;
ALTER TABLE "external_work_item_references" ADD CONSTRAINT "external_work_item_references_project_id_fkey" FOREIGN KEY ("project_id") REFERENCES "projects"("id") ON DELETE RESTRICT ON UPDATE CASCADE;
ALTER TABLE "external_work_item_references" ADD CONSTRAINT "external_work_item_references_work_item_id_fkey" FOREIGN KEY ("work_item_id") REFERENCES "work_items"("id") ON DELETE RESTRICT ON UPDATE CASCADE;
ALTER TABLE "project_milestones" ADD CONSTRAINT "project_milestones_project_id_fkey" FOREIGN KEY ("project_id") REFERENCES "projects"("id") ON DELETE RESTRICT ON UPDATE CASCADE;
ALTER TABLE "project_documents" ADD CONSTRAINT "project_documents_project_id_fkey" FOREIGN KEY ("project_id") REFERENCES "projects"("id") ON DELETE RESTRICT ON UPDATE CASCADE;
ALTER TABLE "project_documents" ADD CONSTRAINT "project_documents_uploader_id_fkey" FOREIGN KEY ("uploader_id") REFERENCES "users"("id") ON DELETE SET NULL ON UPDATE CASCADE;
ALTER TABLE "work_logs" ADD CONSTRAINT "work_logs_user_id_fkey" FOREIGN KEY ("user_id") REFERENCES "users"("id") ON DELETE CASCADE ON UPDATE CASCADE;
ALTER TABLE "work_logs" ADD CONSTRAINT "work_logs_project_id_fkey" FOREIGN KEY ("project_id") REFERENCES "projects"("id") ON DELETE RESTRICT ON UPDATE CASCADE;
ALTER TABLE "work_logs" ADD CONSTRAINT "work_logs_work_item_id_fkey" FOREIGN KEY ("work_item_id") REFERENCES "work_items"("id") ON DELETE RESTRICT ON UPDATE CASCADE;
ALTER TABLE "activity_logs" ADD CONSTRAINT "activity_logs_user_id_fkey" FOREIGN KEY ("user_id") REFERENCES "users"("id") ON DELETE RESTRICT ON UPDATE RESTRICT;
ALTER TABLE "activity_logs" ADD CONSTRAINT "activity_logs_project_id_fkey" FOREIGN KEY ("project_id") REFERENCES "projects"("id") ON DELETE RESTRICT ON UPDATE RESTRICT;

CREATE TRIGGER "pms_stamp_user" BEFORE INSERT OR UPDATE ON "users" FOR EACH ROW EXECUTE FUNCTION pms_stamp_timestamps();
CREATE TRIGGER "pms_stamp_company" BEFORE INSERT OR UPDATE ON "companies" FOR EACH ROW EXECUTE FUNCTION pms_stamp_timestamps();
CREATE TRIGGER "pms_stamp_project" BEFORE INSERT OR UPDATE ON "projects" FOR EACH ROW EXECUTE FUNCTION pms_stamp_timestamps();
CREATE TRIGGER "pms_stamp_project_member" BEFORE INSERT OR UPDATE ON "project_members" FOR EACH ROW EXECUTE FUNCTION pms_stamp_timestamps();
CREATE TRIGGER "pms_stamp_work_items" BEFORE INSERT OR UPDATE ON "work_items" FOR EACH ROW EXECUTE FUNCTION pms_stamp_timestamps();
CREATE TRIGGER "pms_stamp_external_project_mappings" BEFORE INSERT OR UPDATE ON "external_project_mappings" FOR EACH ROW EXECUTE FUNCTION pms_stamp_timestamps();
CREATE TRIGGER "pms_stamp_external_work_item_reference" BEFORE INSERT OR UPDATE ON "external_work_item_references" FOR EACH ROW EXECUTE FUNCTION pms_stamp_timestamps();
CREATE TRIGGER "pms_stamp_milestone" BEFORE INSERT OR UPDATE ON "project_milestones" FOR EACH ROW EXECUTE FUNCTION pms_stamp_timestamps();
CREATE TRIGGER "pms_stamp_document" BEFORE INSERT OR UPDATE ON "project_documents" FOR EACH ROW EXECUTE FUNCTION pms_stamp_timestamps();
CREATE TRIGGER "pms_stamp_work_logs" BEFORE INSERT OR UPDATE ON "work_logs" FOR EACH ROW EXECUTE FUNCTION pms_stamp_timestamps();
CREATE TRIGGER "pms_stamp_activity_log" BEFORE INSERT ON "activity_logs" FOR EACH ROW EXECUTE FUNCTION pms_stamp_created_at();
CREATE TRIGGER "pms_activity_log_immutable" BEFORE UPDATE OR DELETE ON "activity_logs" FOR EACH ROW EXECUTE FUNCTION pms_reject_immutable_row();
CREATE TRIGGER "pms_schema_migrations_immutable" BEFORE UPDATE OR DELETE ON "schema_migrations" FOR EACH ROW EXECUTE FUNCTION pms_reject_immutable_row();

-- Database-visible documentation for every table and column.

COMMENT ON TABLE "users" IS 'User profiles, owner lookup and UI preferences used by the current application.';
COMMENT ON COLUMN "users"."id" IS 'Local primary key generated by this table identity sequence; gaps are allowed.';
COMMENT ON COLUMN "users"."public_id" IS 'Immutable random UUIDv4 for public API and frontend references; internal relations use the numeric id.';
COMMENT ON COLUMN "users"."email" IS 'Unique user email address used for owner identification.';
COMMENT ON COLUMN "users"."name" IS 'User display name.';
COMMENT ON COLUMN "users"."password_hash" IS 'Stored password hash from the legacy authentication model; never a plaintext password.';
COMMENT ON COLUMN "users"."role" IS 'Account role label such as member, manager or admin; separate from a work item functional role.';
COMMENT ON COLUMN "users"."avatar_url" IS 'Optional profile image URL; Settings accepts HTTPS URLs.';
COMMENT ON COLUMN "users"."phone" IS 'Optional user telephone number stored as text.';
COMMENT ON COLUMN "users"."theme" IS 'Selected application theme: light, dark or special-dark.';
COMMENT ON COLUMN "users"."locale" IS 'Selected application language: th or en.';
COMMENT ON COLUMN "users"."status" IS 'User availability or account status label; defaults to Active.';
COMMENT ON COLUMN "users"."joined_at" IS 'Original user join timestamp; separate from record creation time.';
COMMENT ON COLUMN "users"."created_at" IS 'Local record creation time in Asia/Bangkok wall-clock time, with millisecond precision.';
COMMENT ON COLUMN "users"."updated_at" IS 'Local time of the last business data change in Asia/Bangkok; unchanged on no-op writes.';

COMMENT ON TABLE "companies" IS 'Customer companies to which PMS projects belong.';
COMMENT ON COLUMN "companies"."id" IS 'Local primary key generated by this table identity sequence; gaps are allowed.';
COMMENT ON COLUMN "companies"."public_id" IS 'Immutable random UUIDv4 for public API and frontend references; internal relations use the numeric id.';
COMMENT ON COLUMN "companies"."code" IS 'Optional unique stable company code; dhas identifies the built-in Dhas company.';
COMMENT ON COLUMN "companies"."display_name" IS 'Optional short company display name.';
COMMENT ON COLUMN "companies"."location" IS 'Optional company location label.';
COMMENT ON COLUMN "companies"."name" IS 'Company name.';
COMMENT ON COLUMN "companies"."industry" IS 'Optional business industry label.';
COMMENT ON COLUMN "companies"."email" IS 'Optional company contact email address.';
COMMENT ON COLUMN "companies"."phone" IS 'Optional company contact telephone number.';
COMMENT ON COLUMN "companies"."address" IS 'Optional company postal address.';
COMMENT ON COLUMN "companies"."website_url" IS 'Optional company website address.';
COMMENT ON COLUMN "companies"."logo_url" IS 'Optional company logo location.';
COMMENT ON COLUMN "companies"."description" IS 'Optional descriptive text for this record.';
COMMENT ON COLUMN "companies"."created_at" IS 'Local record creation time in Asia/Bangkok wall-clock time, with millisecond precision.';
COMMENT ON COLUMN "companies"."updated_at" IS 'Local time of the last business data change in Asia/Bangkok; unchanged on no-op writes.';

COMMENT ON TABLE "projects" IS 'PMS projects, their planning dates and customer company.';
COMMENT ON COLUMN "projects"."id" IS 'Local primary key generated by this table identity sequence; gaps are allowed.';
COMMENT ON COLUMN "projects"."public_id" IS 'Immutable random UUIDv4 for public API and frontend references; internal relations use the numeric id.';
COMMENT ON COLUMN "projects"."name" IS 'Project name shown in project selection and reporting.';
COMMENT ON COLUMN "projects"."description" IS 'Optional descriptive text for this record.';
COMMENT ON COLUMN "projects"."status" IS 'Project lifecycle label: Planning, In Progress, Review, Completed or On Hold.';
COMMENT ON COLUMN "projects"."priority" IS 'Project priority label: Low, Medium, High or Critical.';
COMMENT ON COLUMN "projects"."start_date" IS 'Planned start as a Bangkok calendar date, without a time component.';
COMMENT ON COLUMN "projects"."due_date" IS 'Planned due date as a Bangkok calendar date, without a time component.';
COMMENT ON COLUMN "projects"."budget_amount" IS 'Optional legacy project budget amount; currency is not represented by the current model.';
COMMENT ON COLUMN "projects"."spent_amount" IS 'Optional legacy recorded spending amount; defaults to zero; currency is not represented.';
COMMENT ON COLUMN "projects"."progress_percent" IS 'Legacy stored completion percentage; current API derives progress from work item statuses.';
COMMENT ON COLUMN "projects"."color" IS 'Optional project display color used for visual identification.';
COMMENT ON COLUMN "projects"."created_at" IS 'Local record creation time in Asia/Bangkok wall-clock time, with millisecond precision.';
COMMENT ON COLUMN "projects"."updated_at" IS 'Local time of the last business data change in Asia/Bangkok; unchanged on no-op writes.';
COMMENT ON COLUMN "projects"."creator_id" IS 'Optional creator user ID; becomes NULL when the creator is deleted.';
COMMENT ON COLUMN "projects"."company_id" IS 'Required customer company ID referencing companies.id.';

COMMENT ON TABLE "project_members" IS 'Project membership records; currently queried by the Project deletion history guard.';
COMMENT ON COLUMN "project_members"."id" IS 'Local primary key generated by this table identity sequence; gaps are allowed.';
COMMENT ON COLUMN "project_members"."public_id" IS 'Immutable random UUIDv4 for public API and frontend references; internal relations use the numeric id.';
COMMENT ON COLUMN "project_members"."role" IS 'Project membership role label: member, lead or manager.';
COMMENT ON COLUMN "project_members"."joined_at" IS 'Original time the user joined this project; separate from local record timestamps.';
COMMENT ON COLUMN "project_members"."project_id" IS 'Local PMS project ID referencing projects.id.';
COMMENT ON COLUMN "project_members"."user_id" IS 'Local user ID referencing users.id.';
COMMENT ON COLUMN "project_members"."created_at" IS 'Local record creation time in Asia/Bangkok wall-clock time, with millisecond precision.';
COMMENT ON COLUMN "project_members"."updated_at" IS 'Local time of the last business data change in Asia/Bangkok; unchanged on no-op writes.';

COMMENT ON TABLE "work_items" IS 'Unified incidents, issues and tasks used by the board, work item list and reporting.';
COMMENT ON COLUMN "work_items"."id" IS 'Local primary key generated by this table identity sequence; gaps are allowed.';
COMMENT ON COLUMN "work_items"."public_id" IS 'Immutable random UUIDv4 for public API and frontend references; internal relations use the numeric id.';
COMMENT ON COLUMN "work_items"."title" IS 'Work item title.';
COMMENT ON COLUMN "work_items"."description" IS 'Optional descriptive text for this record.';
COMMENT ON COLUMN "work_items"."kind" IS 'Work item category: Incident, Issue or Task.';
COMMENT ON COLUMN "work_items"."priority" IS 'Work item priority: none, low, medium, high or urgent.';
COMMENT ON COLUMN "work_items"."functional_role" IS 'Optional work function: Developer, infra or SA; separate from account and membership roles.';
COMMENT ON COLUMN "work_items"."status" IS 'Workflow state, retaining the current public values including in-progress, sa-testing and pm-testing.';
COMMENT ON COLUMN "work_items"."type_labels" IS 'User-defined type labels exposed as types by the current WorkItem API; defaults to an empty array.';
COMMENT ON COLUMN "work_items"."work_date" IS 'Optional scheduled work date as a Bangkok calendar date.';
COMMENT ON COLUMN "work_items"."due_date" IS 'Optional work item due date as a Bangkok calendar date.';
COMMENT ON COLUMN "work_items"."submitted_at" IS 'First submission time stamped for submitted workflow states; not the completion time.';
COMMENT ON COLUMN "work_items"."created_at" IS 'Local record creation time in Asia/Bangkok wall-clock time, with millisecond precision.';
COMMENT ON COLUMN "work_items"."updated_at" IS 'Local time of the last business data change in Asia/Bangkok; unchanged on no-op writes.';
COMMENT ON COLUMN "work_items"."project_id" IS 'Local PMS project ID referencing projects.id.';
COMMENT ON COLUMN "work_items"."assignee_id" IS 'Required assigned user ID referencing users.id.';

COMMENT ON TABLE "external_project_mappings" IS 'Owner-managed mappings from an external provider project or repository to a local PMS project.';
COMMENT ON COLUMN "external_project_mappings"."id" IS 'Local primary key generated by this table identity sequence; gaps are allowed.';
COMMENT ON COLUMN "external_project_mappings"."public_id" IS 'Immutable random UUIDv4 for public API and frontend references; internal relations use the numeric id.';
COMMENT ON COLUMN "external_project_mappings"."provider" IS 'External provider key, for example gitlab or github; defaults to gitlab for the current integration.';
COMMENT ON COLUMN "external_project_mappings"."instance_url" IS 'Canonical base URL identifying the provider instance, for example a GitLab host or GitHub host.';
COMMENT ON COLUMN "external_project_mappings"."external_project_id" IS 'Stable provider project or repository identifier stored as text; not a local PMS project ID.';
COMMENT ON COLUMN "external_project_mappings"."project_id" IS 'Local PMS project ID referencing projects.id.';
COMMENT ON COLUMN "external_project_mappings"."approved_label_map" IS 'Owner-approved JSON mapping of source provider labels to PMS type labels.';
COMMENT ON COLUMN "external_project_mappings"."first_sync_approved_at" IS 'Optional time the owner approved the first sync for this mapping.';
COMMENT ON COLUMN "external_project_mappings"."created_at" IS 'Local record creation time in Asia/Bangkok wall-clock time, with millisecond precision.';
COMMENT ON COLUMN "external_project_mappings"."updated_at" IS 'Local time of the last business data change in Asia/Bangkok; unchanged on no-op writes.';

COMMENT ON TABLE "external_work_item_references" IS 'Imported external issue identity and sync timestamps, retained independently of its project mapping.';
COMMENT ON COLUMN "external_work_item_references"."id" IS 'Local primary key generated by this table identity sequence; gaps are allowed.';
COMMENT ON COLUMN "external_work_item_references"."public_id" IS 'Immutable random UUIDv4 for public API and frontend references; internal relations use the numeric id.';
COMMENT ON COLUMN "external_work_item_references"."provider" IS 'External issue provider key, for example gitlab or github; defaults to gitlab for the current importer.';
COMMENT ON COLUMN "external_work_item_references"."instance_url" IS 'Canonical base URL identifying the source provider instance; distinct from the issue web URL.';
COMMENT ON COLUMN "external_work_item_references"."external_project_id" IS 'Stable external project or repository identifier; independent of the local PMS project_id.';
COMMENT ON COLUMN "external_work_item_references"."external_issue_id" IS 'Stable issue identifier returned by the provider; part of the provider-scoped deduplication identity.';
COMMENT ON COLUMN "external_work_item_references"."external_issue_number" IS 'Issue number scoped to the external project or repository, such as GitLab IID; distinct from the stable external issue ID.';
COMMENT ON COLUMN "external_work_item_references"."external_url" IS 'Source issue web URL.';
COMMENT ON COLUMN "external_work_item_references"."project_id" IS 'Local PMS project ID captured on import and compared with the current mapping to detect identity conflicts.';
COMMENT ON COLUMN "external_work_item_references"."remote_created_at" IS 'Source provider issue creation time normalized to Bangkok wall-clock time; not local creation time.';
COMMENT ON COLUMN "external_work_item_references"."remote_updated_at" IS 'Source provider issue update time used to reject stale sync payloads.';
COMMENT ON COLUMN "external_work_item_references"."last_synced_at" IS 'Bangkok wall-clock time of the last successful sync or no-change sync check.';
COMMENT ON COLUMN "external_work_item_references"."work_item_id" IS 'Unique local work item ID; one external reference per imported work item.';
COMMENT ON COLUMN "external_work_item_references"."created_at" IS 'Local record creation time in Asia/Bangkok wall-clock time, with millisecond precision.';
COMMENT ON COLUMN "external_work_item_references"."updated_at" IS 'Local time of the last business data change in Asia/Bangkok; unchanged on no-op writes.';

COMMENT ON TABLE "project_milestones" IS 'Project milestone records; currently queried by the Project deletion history guard.';
COMMENT ON COLUMN "project_milestones"."id" IS 'Local primary key generated by this table identity sequence; gaps are allowed.';
COMMENT ON COLUMN "project_milestones"."public_id" IS 'Immutable random UUIDv4 for public API and frontend references; internal relations use the numeric id.';
COMMENT ON COLUMN "project_milestones"."name" IS 'Milestone name.';
COMMENT ON COLUMN "project_milestones"."description" IS 'Optional descriptive text for this record.';
COMMENT ON COLUMN "project_milestones"."due_date" IS 'Legacy milestone due timestamp; preserves the existing timestamp type.';
COMMENT ON COLUMN "project_milestones"."status" IS 'Milestone lifecycle label: Not Started, In Progress or Completed.';
COMMENT ON COLUMN "project_milestones"."created_at" IS 'Local record creation time in Asia/Bangkok wall-clock time, with millisecond precision.';
COMMENT ON COLUMN "project_milestones"."updated_at" IS 'Local time of the last business data change in Asia/Bangkok; unchanged on no-op writes.';
COMMENT ON COLUMN "project_milestones"."project_id" IS 'Local PMS project ID referencing projects.id.';

COMMENT ON TABLE "project_documents" IS 'Project file metadata; currently queried by the Project deletion history guard.';
COMMENT ON COLUMN "project_documents"."id" IS 'Local primary key generated by this table identity sequence; gaps are allowed.';
COMMENT ON COLUMN "project_documents"."public_id" IS 'Immutable random UUIDv4 for public API and frontend references; internal relations use the numeric id.';
COMMENT ON COLUMN "project_documents"."name" IS 'Document display name.';
COMMENT ON COLUMN "project_documents"."description" IS 'Optional descriptive text for this record.';
COMMENT ON COLUMN "project_documents"."file_url" IS 'Stored file location or URL.';
COMMENT ON COLUMN "project_documents"."file_size_bytes" IS 'Optional file size measured in bytes.';
COMMENT ON COLUMN "project_documents"."file_type" IS 'Optional stored file type label; the current model does not enforce a MIME format.';
COMMENT ON COLUMN "project_documents"."created_at" IS 'Local record creation time in Asia/Bangkok wall-clock time, with millisecond precision.';
COMMENT ON COLUMN "project_documents"."updated_at" IS 'Local time of the last business data change in Asia/Bangkok; unchanged on no-op writes.';
COMMENT ON COLUMN "project_documents"."project_id" IS 'Optional local project ID; documents can exist without a project.';
COMMENT ON COLUMN "project_documents"."uploader_id" IS 'Optional uploading user ID; becomes NULL when that user is deleted.';

COMMENT ON TABLE "work_logs" IS 'Daily work logs with decimal hours, user, project and optional work item linkage.';
COMMENT ON COLUMN "work_logs"."id" IS 'Local primary key generated by this table identity sequence; gaps are allowed.';
COMMENT ON COLUMN "work_logs"."public_id" IS 'Immutable random UUIDv4 for public API and frontend references; internal relations use the numeric id.';
COMMENT ON COLUMN "work_logs"."description" IS 'Optional descriptive text for this record.';
COMMENT ON COLUMN "work_logs"."remarks" IS 'Optional additional notes about the work log.';
COMMENT ON COLUMN "work_logs"."hours" IS 'Logged work duration in decimal hours with precision 65 and scale 30; API validates a positive value.';
COMMENT ON COLUMN "work_logs"."work_date" IS 'Bangkok calendar date on which the work was performed; defaults to the current Bangkok date.';
COMMENT ON COLUMN "work_logs"."status" IS 'Optional work status recorded with this log; independent of the current work item status.';
COMMENT ON COLUMN "work_logs"."created_at" IS 'Local record creation time in Asia/Bangkok wall-clock time, with millisecond precision.';
COMMENT ON COLUMN "work_logs"."updated_at" IS 'Local time of the last business data change in Asia/Bangkok; unchanged on no-op writes.';
COMMENT ON COLUMN "work_logs"."user_id" IS 'Local user ID referencing users.id.';
COMMENT ON COLUMN "work_logs"."project_id" IS 'Optional local project ID in storage; the current API derives it from the linked work item.';
COMMENT ON COLUMN "work_logs"."work_item_id" IS 'Optional local work item ID in storage; required by current work log create requests.';

COMMENT ON TABLE "activity_logs" IS 'Append-only activity history; currently queried by the Project deletion history guard.';
COMMENT ON COLUMN "activity_logs"."id" IS 'Local primary key generated by this table identity sequence; gaps are allowed.';
COMMENT ON COLUMN "activity_logs"."public_id" IS 'Immutable random UUIDv4 for public API and frontend references; internal relations use the numeric id.';
COMMENT ON COLUMN "activity_logs"."action" IS 'Recorded action label, for example created, updated or deleted.';
COMMENT ON COLUMN "activity_logs"."entity" IS 'Type of entity affected by the action, for example project or work_item.';
COMMENT ON COLUMN "activity_logs"."entity_id" IS 'Opaque affected entity identifier; polymorphic historical text, not a numeric foreign key.';
COMMENT ON COLUMN "activity_logs"."description" IS 'Optional descriptive text for this record.';
COMMENT ON COLUMN "activity_logs"."metadata" IS 'Optional JSON context for the recorded action.';
COMMENT ON COLUMN "activity_logs"."created_at" IS 'Local record creation time in Asia/Bangkok wall-clock time, with millisecond precision.';
COMMENT ON COLUMN "activity_logs"."user_id" IS 'Optional actor user ID; deleting or renumbering a referenced user is restricted to preserve the log.';
COMMENT ON COLUMN "activity_logs"."project_id" IS 'Optional related project ID; deleting or renumbering a referenced project is restricted.';

COMMENT ON TABLE "schema_migrations" IS 'Immutable history of SQL artifacts applied by scripts/sql-migrate.mjs.';
COMMENT ON COLUMN "schema_migrations"."id" IS 'Local primary key generated by this table identity sequence; gaps are allowed.';
COMMENT ON COLUMN "schema_migrations"."public_id" IS 'Immutable random UUIDv4 for public API and frontend references; internal relations use the numeric id.';
COMMENT ON COLUMN "schema_migrations"."version" IS 'Unique four-digit migration version validated by the SQL runner.';
COMMENT ON COLUMN "schema_migrations"."checksum" IS 'SHA-256 hex checksum of the exact applied SQL artifact bytes.';
COMMENT ON COLUMN "schema_migrations"."schema_revision" IS 'Schema revision from the migration manifest at application time.';
COMMENT ON COLUMN "schema_migrations"."status" IS 'Migration result; constrained to applied because failed transactions leave no history row.';
COMMENT ON COLUMN "schema_migrations"."applied_at" IS 'Bangkok wall-clock time at which the migration history row was recorded.';
COMMENT ON COLUMN "schema_migrations"."script_name" IS 'Relative SQL artifact path within database/.';
COMMENT ON COLUMN "schema_migrations"."target_label" IS 'Validated non-secret label of the isolated migration target.';

