import assert from 'node:assert/strict';
import test from 'node:test';
import { readFile } from 'node:fs/promises';
import { dirname, resolve } from 'node:path';
import { fileURLToPath } from 'node:url';
import { BUSINESS_TABLES, MUTABLE_TIMESTAMP_TABLES, TECHNICAL_TABLES, loadArtifacts } from '../../scripts/sql-artifacts.mjs';
import { diffFingerprints } from '../../scripts/sql-catalog.mjs';

const root = resolve(dirname(fileURLToPath(import.meta.url)), '../..');

const schema = await readFile(new URL('../../database/schema.sql', import.meta.url), 'utf8');
const prismaSchema = await readFile(new URL('../../prisma/schema.prisma', import.meta.url), 'utf8');
const entrypoint = await readFile(new URL('../../scripts/docker-entrypoint-migrate.sh', import.meta.url), 'utf8');
const packageJson = JSON.parse(await readFile(new URL('../../package.json', import.meta.url), 'utf8'));

function tableBody(name) {
  const match = new RegExp(`CREATE TABLE "${name}" \\(([\\s\\S]*?)\\n\\);`).exec(schema);
  assert.ok(match, `Missing table ${name}`);
  return match[1];
}

test('TC-31-01 schema snapshot declares only runtime-used business tables and migration history', () => {
  for (const name of [...BUSINESS_TABLES, ...TECHNICAL_TABLES]) assert.match(schema, new RegExp(`CREATE TABLE "${name}"`));
  assert.equal(schema.match(/CREATE TABLE /g).length, BUSINESS_TABLES.length + TECHNICAL_TABLES.length);
  assert.equal(schema.match(/BIGINT GENERATED BY DEFAULT AS IDENTITY \(START WITH 1 INCREMENT BY 1 NO CYCLE\)/g).length, BUSINESS_TABLES.length + TECHNICAL_TABLES.length);
  assert.doesNotMatch(schema, /CREATE TABLE "(?:Comment|Notification|comments|notifications|legacy_id_mappings)"/);
  assert.doesNotMatch(schema, /timestamptz|TIMESTAMPTZ|cuid\(|IF NOT EXISTS/i);
  assert.doesNotMatch(schema, /postgres(?:ql)?:\/\//i);
  assert.doesNotMatch(schema, /\binsert\s+into\b/i);
  const loaded = loadArtifacts(root);
  assert.equal(loaded.revision, '31.0.0');
  assert.equal(loaded.migrations[0].script, 'database/schema.sql');
});

test('every table has a unique database-generated public UUID and all FKs remain numeric', () => {
  for (const name of [...BUSINESS_TABLES, ...TECHNICAL_TABLES]) {
    const body = tableBody(name);
    assert.match(body, /"public_id" UUID NOT NULL DEFAULT pg_catalog\.gen_random_uuid\(\)/);
    assert.ok(body.includes(`CONSTRAINT "${name}_public_id_key" UNIQUE ("public_id")`));
  }
  for (const [, table, column, target, key] of schema.matchAll(/ALTER TABLE "([^"]+)" ADD CONSTRAINT "[^"]+" FOREIGN KEY \("([^"]+)"\) REFERENCES "([^"]+)"\("([^"]+)"\)/g)) {
    assert.equal(key, 'id');
    assert.ok(tableBody(table).includes(`"${column}" BIGINT`));
    assert.ok(tableBody(target).includes('"id" BIGINT'));
  }
  assert.match(schema, /TG_OP = 'UPDATE' AND NEW\.public_id IS DISTINCT FROM OLD\.public_id/);
});

test('TC-31-02 snapshot preserves values and uses clear names with local numeric project references', () => {
  assert.match(schema, /'in-progress', 'blocked', 'sa-testing', 'pm-testing'/);
  assert.match(schema, /DECIMAL\(65,30\)/);
  assert.match(schema, /"type_labels" TEXT\[\]/);
  assert.match(schema, /JSONB/);
  assert.equal(schema.match(/TIMESTAMP\(3\) WITHOUT TIME ZONE/g).length > 0, true);
  for (const name of MUTABLE_TIMESTAMP_TABLES) {
    const body = tableBody(name);
    assert.match(body, /"created_at" TIMESTAMP\(3\) WITHOUT TIME ZONE NOT NULL/);
    assert.match(body, /"updated_at" TIMESTAMP\(3\) WITHOUT TIME ZONE NOT NULL/);
  }
  const activity = tableBody('activity_logs');
  assert.match(activity, /"created_at"/);
  assert.doesNotMatch(activity, /updated_at/);
  assert.match(activity, /"entity_id" TEXT NOT NULL/);
  const external = tableBody('external_work_item_references');
  assert.match(external, /"project_id" BIGINT NOT NULL/);
  assert.match(external, /"remote_created_at"/);
  assert.match(external, /"created_at"/);
  const member = tableBody('project_members');
  assert.match(member, /"joined_at"/);
  assert.match(member, /"created_at"/);
  const history = tableBody('schema_migrations');
  assert.match(history, /"applied_at"/);
  assert.doesNotMatch(history, /updated_at/);
  assert.match(schema, /"activity_logs_user_id_fkey" FOREIGN KEY \("user_id"\) REFERENCES "users"\("id"\) ON DELETE RESTRICT ON UPDATE RESTRICT/);
  assert.match(schema, /"activity_logs_project_id_fkey" FOREIGN KEY \("project_id"\) REFERENCES "projects"\("id"\) ON DELETE RESTRICT ON UPDATE RESTRICT/);
  assert.match(schema, /"external_work_item_references_project_id_fkey" FOREIGN KEY \("project_id"\) REFERENCES "projects"\("id"\) ON DELETE RESTRICT ON UPDATE CASCADE/);
  assert.match(tableBody('users'), /"password_hash" TEXT NOT NULL/);
  assert.match(tableBody('work_logs'), /"work_date" DATE NOT NULL/);
  assert.match(tableBody('work_items'), /"functional_role" "work_item_role"/);
});

test('schema documents every table and column with PostgreSQL comments and uses snake_case identifiers', () => {
  const tables = [...schema.matchAll(/CREATE TABLE "([^"]+)" \(([\s\S]*?)\n\);/g)];
  const tableComments = [...schema.matchAll(/COMMENT ON TABLE "([^"]+)" IS '((?:[^']|'')+)';/g)];
  const columnComments = [...schema.matchAll(/COMMENT ON COLUMN "([^"]+)"\."([^"]+)" IS '((?:[^']|'')+)';/g)];
  const tableNames = tables.map(([, name]) => name).sort();
  const columnNames = tables.flatMap(([, name, body]) => [...body.matchAll(/^    "([^"]+)" /gm)].map(([, column]) => `${name}.${column}`)).sort();
  assert.deepEqual(tableComments.map(([, name]) => name).sort(), tableNames);
  assert.deepEqual(columnComments.map(([, name, column]) => `${name}.${column}`).sort(), columnNames);
  for (const [, name, body] of tables) {
    assert.match(name, /^[a-z][a-z0-9_]*$/);
    for (const [, column] of body.matchAll(/^    "([^"]+)" /gm)) assert.match(column, /^[a-z][a-z0-9_]*$/);
  }
  for (const [, identifier] of schema.matchAll(/(?:CONSTRAINT|CREATE (?:UNIQUE )?INDEX|CREATE TYPE|CREATE TRIGGER) "([^"]+)"/g)) {
    assert.match(identifier, /^[a-z][a-z0-9_]*$/);
    assert.ok(identifier.length <= 63, `${identifier} exceeds the PostgreSQL identifier limit`);
  }
});

test('external mappings and issue identities use provider-neutral names and provider-scoped unique keys', () => {
  const mappings = tableBody('external_project_mappings');
  const references = tableBody('external_work_item_references');
  for (const body of [mappings, references]) {
    assert.match(body, /"provider" TEXT NOT NULL DEFAULT 'gitlab'/);
    assert.match(body, /"instance_url" TEXT NOT NULL/);
    assert.match(body, /"external_project_id" TEXT NOT NULL/);
    assert.doesNotMatch(body, /"gitlab_[a-z_]+"/);
  }
  assert.match(references, /"external_issue_id" TEXT NOT NULL/);
  assert.match(references, /"external_issue_number" TEXT NOT NULL/);
  assert.match(schema, /"external_project_mappings_source_key" ON "external_project_mappings"\("provider", "instance_url", "external_project_id"\)/);
  assert.match(schema, /"external_work_item_references_source_key" ON "external_work_item_references"\("provider", "instance_url", "external_project_id", "external_issue_id"\)/);
});

test('tables retained for Project deletion checks are still queried by the current API', async () => {
  const route = await readFile(new URL('../../app/api/projects/[id]/route.ts', import.meta.url), 'utf8');
  for (const relation of ['documents', 'milestones', 'activityLogs', 'members']) assert.match(route, new RegExp(`${relation}: true`));
  assert.ok(BUSINESS_TABLES.includes('project_documents'));
  assert.ok(BUSINESS_TABLES.includes('project_milestones'));
  assert.ok(BUSINESS_TABLES.includes('activity_logs'));
  assert.ok(BUSINESS_TABLES.includes('project_members'));
});

test('TC-33-13 active Prisma runtime and migrate entrypoint use the SQL workflow', () => {
  assert.match(prismaSchema, /publicId\s+String\s+@unique/);
  assert.match(prismaSchema, /BigInt\s+@id @default\(autoincrement\(\)\)/);
  assert.match(prismaSchema, /provider\s*=\s*"postgresql"/);
  assert.doesNotMatch(prismaSchema, /@default\(cuid\(\)\)|@updatedAt/);
  assert.match(entrypoint, /db-schema-rollout-gate\.mjs/);
  assert.match(entrypoint, /sql-runtime\.mjs apply/);
  assert.doesNotMatch(entrypoint, /db-push-safe\.sh|prisma db seed/);
  assert.equal(packageJson.scripts['test:sql-schema'], 'node tests/run.mjs sql-schema');
  assert.equal(packageJson.scripts['test:sql-migrations-docker'], 'node tests/run.mjs sql-migrations-docker');
  assert.match(packageJson.scripts.test, /tests\/run\.mjs/);
});

test('TC-31-15 fingerprint comparison detects an added catalog line and ignores order', () => {
  const left = 'column companies id bigint\ntrigger pms_stamp_company';
  const right = 'trigger pms_stamp_company\ncolumn companies id bigint';
  assert.equal(diffFingerprints(left, right).equal, true);
  const drifted = diffFingerprints(left, `${right}\ncolumn companies drift_marker text`);
  assert.equal(drifted.equal, false);
  assert.deepEqual(drifted.onlyRight, ['column companies drift_marker text']);
});
